name: linting and formatting

on:
  pull_request:
    branches: [main]

jobs:
  ruff:
    name: Ruff checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          python-version: 3.12

      - name: Linting & Formatting
        run: make ruff

      - name: Type Check
        run: make ty

      - name: Check if changes required
        run: |
          if ! git diff --exit-code; then
            echo "❌ Ruff introduced changes. Please run 'ruff check --fix' and 'ruff format' locally."
            exit 1
          fi
